services:
    admin-django:
        container_name: admin-django
        build:
            context: ./backend/django
            dockerfile: Dockerfile
        command: sh /app/scripts/entrypoint.sh
        env_file:
            - ./backend/django/.env
        volumes:
            - ./backend/django:/app
        ports:
            - '8000:8000'
        networks:
            - app_net
networks:
    app_net:
        external: true
