services:
  admin_django:
    image: johnsantamaria/admin_django:v1.0.0-beta
    env_file:
      - ./backend/django/.env
    volumes:
      - ./backend/django:/app
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  app_net:
    external: true