services:
    database:
        image: postgres:15
        container_name: database
        restart: always
        env_file:
            - .env.db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - app_net

volumes:
    postgres_data:

networks:
    app_net:
        external: true
