services:
    database:
        image: postgres:15-alpine
        container_name: database
        restart: always
        env_file:
            - .env.db
        environment:
            - POSTGRES_INITDB_ARGS=--locale=en_US.utf8
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres_data:
