services:
    base_integration:
        container_name: base_integration
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn app.main:app --host 0.0.0.0 --port 8080
        env_file:
            - .env.prod
        environment:
            RUNNING_IN_DOCKER: '1'
        ports:
            - '8080:8080'
        networks:
            - app_net
networks:
    app_net:
        external: true
