services:
    openai-integration:
        container_name: openai-integration
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn app.main:app --host 0.0.0.0 --port 8003

        env_file:
            - .env.prod
        volumes:
            - ./app:/code
        ports:
            - '8003:8003'
        networks:
            - app_net

networks:
    app_net:
        external: true
