services:
    admin_django:
        container_name: admin_django
        build:
            context: .
            dockerfile: Dockerfile
        command: sh /app/scripts/entrypoint.sh
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        networks:
            - app_net
networks:
    app_net:
        external: true
