services:
    database:
        image: postgres:15
        container_name: postgres_db
        restart: always
        env_file:
            - .env.db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    admin_django:
        container_name: admin_django
        build:
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - .env
        volumes:
            - ./:/app
        ports:
            - '8000:8000'
        depends_on:
            - database

volumes:
    postgres_data:
