services:
    ocr_integration:
        container_name: ocr_integration
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn app.main:app --host 0.0.0.0 --port 8001
        env_file:
            - .env.prod
        volumes:
            - ./app:/code
        ports:
            - '8001:8001'
        networks:
            - app_net

networks:
    app_net:
        external: true
